# Generated by Django 5.1.3 on 2024-11-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='Название отдела')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='MTS.department', verbose_name='Отдел')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='MTS.employee', verbose_name='Непосредственный начальник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='MTS.employee', verbose_name='Руководитель отдела'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('Pending', 'В ожидании'), ('In Progress', 'В процессе'), ('Completed', 'Выполнено')], default='Pending', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('Low', 'Низкий'), ('Medium', 'Средний'), ('High', 'Высокий')], default='Medium', max_length=10, verbose_name='Приоритет')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='MTS.employee', verbose_name='Назначено сотрудником')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='MTS.employee', verbose_name='Назначено сотруднику')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='EmployeeHierarchyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.PositiveIntegerField(verbose_name='Уровень вложенности')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descendant_set', to='MTS.employee', verbose_name='Предок')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_set', to='MTS.employee', verbose_name='Потомок')),
            ],
            options={
                'verbose_name': 'Запись в таблице замыканий',
                'verbose_name_plural': 'Таблица замыканий',
                'ordering': ['depth'],
                'unique_together': {('ancestor', 'descendant')},
            },
        ),
    ]
